# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4969f21d480d5f04b908bf5fdfd2a76eea753298b3dc95650d8aa774f3ed4920ca341d5a305421d965d05e77c6a49e6d45ea3576636797937db3516ccc82f6a0

test:
  secret_key_base: 626de124e2787c61a878f7a6994224dcf2acb021828a50160ff7af22a4af9cb8c4a266f333c12065b6f4016fee32b44ff7041951094bdcf8be3d96675a6a1363

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
